### ISSUE TITLE
multiple sub-apps cannot mount on the same root

### ISSUE THREAD

**Issue by talentlessguy** [deno-libs/tinyhttp#14]
```js
import { App } from 'https://denopkg.com/deno-libs/tinyhttp@master/mod.ts'
import { makeFetch } from 'https://deno.land/x/superfetch@1.0.4/mod.ts'

const app = new App()

const route1 = new App()
route1.get('/route1', (_req, res) => void res.end('route1'))

const route2 = new App()
route2.get('/route2', (_req, res) => void res.end('route2'))

app.use(route1)
app.use(route2)

const res1 = await makeFetch(app.handler)('/route1')
res1.expect('route1')

const res2 = await makeFetch(app.handler)('/route2')
res2.expect('route2')
```

**Comment by aarontravass** [comment]
I'm not sure but there seems to be a problem with either `deno` or `makeFetch`.
If you run this code, it still breaks, at least for me
```typescript
 const app = new App()

      const route1 = new App()

      route1.get('/route1', (_req, res) => void res.end('route1'))

      app.get('/route2', (_, res)=>void res.end("route2"))

      app.use(route1)  

      console.log("Now testing route2")
      const res2 = await makeFetch(app.handler)('/route2')
      res2.expect('route2')
      console.log("Now testing route1...")
      const res1 = await makeFetch(app.handler)('/route1')
      res1.expect('route1')
```
And add `console.log(_req.url)` at Line [287](https://github.com/deno-libs/tinyhttp/blob/c99be7f7cb452e9fd82d000798b9985156e47c1f/app.ts#L287) 
The output
```typescript
Subapps > multiple sub-apps mount on root ...
------- output -------
Now testing route2
http://localhost:8080/route2
Now testing route1...
Uncaught error from ./tests/core/app.test.ts FAILED
Subapps > multiple sub-apps mount on root ... cancelled (0ms)

 ERRORS 

./tests/core/app.test.ts (uncaught error)
error: (in promise) TypeError: error sending request for url (http://localhost:8080/route1): connection closed before message completed
  const res = await fetch(
              ^
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async fetchEndpoint (https://deno.land/x/superfetch@1.0.4/mod.ts:11:15)
    at async https://deno.land/x/superfetch@1.0.4/mod.ts:55:33
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./tests/core/app.test.ts (uncaught error)

FAILED | 2 passed | 20 failed | 36 ignored (189ms)

error: Test failed
```

Notice that it prints route2 but fails and does not print route1. Which means the second request doesn't reach the router

**Comment by aarontravass** [comment]
In supertest, why are you [closing the connection](https://github.com/deno-libs/superfetch/blob/f3e5b28932a56817ba1a62b085d2f8847efdb17a/mod.ts#L33)?

**Comment by talentlessguy** [comment]
@aarontravass otherwise the test will leak resources, I'm not sure if I should actually close it since I close the listener already tho

**Comment by aarontravass** [comment]
> @aarontravass otherwise the test will leak resources, I'm not sure if I should actually close it since I close the listener already tho

I got it to work but the makeFetch keeps fetching the same port which kinda messes it up

**Comment by aarontravass** [comment]
Alright, It works. but there's a catch. I had to modify superfetch
```ts
export const makeFetch = (h: HandlerOrListener, port?: number)
```
I take the port as an optional arg
And it is processed this way
```ts
const freePort = port || await getFreePort(8080)
```
I believe the `getFreePort`  has a different priority in the promise queue when compared to the `setTimeout` call back queue. And this causes `getFreePort` to always output 8080 even if placed inside the `makeFetchPromise` fn.

**Comment by aarontravass** [comment]
![image](https://github.com/deno-libs/tinyhttp/assets/43901677/1ce1cef8-2f27-4168-8fa7-64d782b70259)
